export const techStacks = {
  markup_Styling: [
    { name: "HTML", category: "Markup" },
    { name: "CSS", category: "Styling" },
    { name: "XML", category: "Markup" },
    { name: "SVG", category: "Markup" },
    { name: "Markdown", category: "Markup" },
    { name: "Sass", category: "Styling" },
    { name: "Less", category: "Styling" },
    { name: "SCSS", category: "Styling" },
    { name: "Stylus", category: "Styling" },
    { name: "Pug", category: "Markup" },
  ],
  programming_languages: [
    { name: "JavaScript", category: "Programming Language" },
    { name: "Python", category: "Programming Language" },
    { name: "Java", category: "Programming Language" },
    { name: "C#", category: "Programming Language" },
    { name: "C++", category: "Programming Language" },
    { name: "TypeScript", category: "Programming Language" },
    { name: "Ruby", category: "Programming Language" },
    { name: "Swift", category: "Programming Language" },
    { name: "Go", category: "Programming Language" },
    { name: "Kotlin", category: "Programming Language" },
    { name: "Rust", category: "Programming Language" },
    { name: "PHP", category: "Programming Language" },
    { name: "Objective-C", category: "Programming Language" },
    { name: "Dart", category: "Programming Language" },
    { name: "Scala", category: "Programming Language" },
    { name: "Haskell", category: "Programming Language" },
    { name: "Shell", category: "Programming Language" },
    { name: "Perl", category: "Programming Language" },
    { name: "R", category: "Programming Language" },
    { name: "Lua", category: "Programming Language" },
    { name: "Groovy", category: "Programming Language" },
  ],

  web_frameworks: [
    { name: "React", category: "Web Framework" },
    { name: "Angular", category: "Web Framework" },
    { name: "Vue.js", category: "Web Framework" },
    { name: "Django", category: "Web Framework" },
    { name: "Flask", category: "Web Framework" },
    { name: "Spring Boot", category: "Web Framework" },
    { name: "Express.js", category: "Web Framework" },
    { name: "Ruby on Rails", category: "Web Framework" },
    { name: "Laravel", category: "Web Framework" },
    { name: "ASP.NET", category: "Web Framework" },
    { name: "Symfony", category: "Web Framework" },
    { name: "Meteor", category: "Web Framework" },
    { name: "NestJS", category: "Web Framework" },
    { name: "FastAPI", category: "Web Framework" },
    { name: "ASP.NET Core", category: "Web Framework" },
    { name: "Play Framework", category: "Web Framework" },
  ],

  mobile_frameworks: [
    { name: "React Native", category: "Mobile Framework" },
    { name: "Flutter", category: "Mobile Framework" },
    { name: "Xamarin", category: "Mobile Framework" },
    { name: "SwiftUI", category: "Mobile Framework" },
    { name: "Android SDK", category: "Mobile Framework" },
    { name: "PhoneGap/Cordova", category: "Mobile Framework" },
  ],

  backend_frameworks: [
    { name: "Node.js", category: "Backend Framework" },
    { name: "Express.js", category: "Backend Framework" },
    { name: "Django", category: "Backend Framework" },
    { name: "Flask", category: "Backend Framework" },
    { name: "Spring Boot", category: "Backend Framework" },
    { name: "Ruby on Rails", category: "Backend Framework" },
    { name: "Laravel", category: "Backend Framework" },
    { name: "ASP.NET", category: "Backend Framework" },
    { name: "Symfony", category: "Backend Framework" },
    { name: "NestJS", category: "Backend Framework" },
    { name: "FastAPI", category: "Backend Framework" },
    { name: "ASP.NET Core", category: "Backend Framework" },
    { name: "Express.js", category: "Backend Framework" },
    { name: "Koa", category: "Backend Framework" },
  ],

  databases: [
    { name: "MySQL", category: "Database" },
    { name: "PostgreSQL", category: "Database" },
    { name: "MongoDB", category: "Database" },
    { name: "SQLite", category: "Database" },
    { name: "Redis", category: "Database" },
    { name: "Oracle", category: "Database" },
    { name: "Microsoft SQL Server", category: "Database" },
    { name: "Cassandra", category: "Database" },
    { name: "Firebase", category: "Database" },
  ],

  devops_tools: [
    { name: "Docker", category: "DevOps Tool" },
    { name: "Kubernetes", category: "DevOps Tool" },
    { name: "Jenkins", category: "DevOps Tool" },
    { name: "GitLab CI/CD", category: "DevOps Tool" },
    { name: "Travis CI", category: "DevOps Tool" },
    { name: "CircleCI", category: "DevOps Tool" },
    { name: "Ansible", category: "DevOps Tool" },
    { name: "Puppet", category: "DevOps Tool" },
    { name: "Terraform", category: "DevOps Tool" },
  ],

  cloud_providers: [
    { name: "Amazon Web Services (AWS)", category: "Cloud Provider" },
    { name: "Microsoft Azure", category: "Cloud Provider" },
    { name: "Google Cloud Platform (GCP)", category: "Cloud Provider" },
    { name: "IBM Cloud", category: "Cloud Provider" },
    { name: "DigitalOcean", category: "Cloud Provider" },
    { name: "Heroku", category: "Cloud Provider" },
  ],

  version_control: [
    { name: "Git", category: "Version Control System" },
    { name: "GitHub", category: "Version Control System" },
    { name: "GitLab", category: "Version Control System" },
  ],
};
